package com.myspace.eat_now_food_delivery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class campaign implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public campaign() {
    }




}